# ============================================================
# SKRIPSI NLP - GOOGLE COLAB TESTING
# Klasifikasi Perilaku Siswa (Reward/Punishment)
# Menggunakan engine dari nlp_engine.py
# ============================================================

import sys
sys.path.insert(0, '.')

from nlp_engine import (
    preprocess_text, naive_bayes, klasifikasi, teks_dikenali,
    dataset_training, master_poin
)

# ============================================================
# DATASET TRAINING (dari tabel dataset_training)
# ============================================================
dataset_training.extend([
    ("Siswa terbukti membawa minuman beralkohol ke lingkungan sekolah", "Punishment"),
    ("Siswa kedapatan menyimpan alkohol saat pemeriksaan sekolah", "Punishment"),
    ("Siswa terbukti mengonsumsi minuman keras di area sekolah", "Punishment"),
    ("Siswa terlibat penggunaan alkohol berdasarkan laporan guru", "Punishment"),
    ("Siswa membawa barang terlarang berupa minuman keras", "Punishment"),
    ("Siswa terbukti menggunakan zat terlarang sesuai hasil pemeriksaan", "Punishment"),
    ("Siswa kedapatan membawa narkotika ke sekolah", "Punishment"),
    ("Siswa terbukti memakai narkoba berdasarkan pembuktian sekolah", "Punishment"),
    ("Siswa terlibat penyalahgunaan psikotropika di lingkungan sekolah", "Punishment"),
    ("Siswa membawa obat terlarang tanpa izin resmi", "Punishment"),
    ("Siswa terbukti menyimpan zat adiktif di tas sekolah", "Punishment"),
    ("Siswa kedapatan menggunakan narkotika saat kegiatan sekolah", "Punishment"),
    ("Siswa terbukti mengedarkan barang terlarang kepada siswa lain", "Punishment"),
    ("Siswa terlibat penjualan minuman keras di lingkungan sekolah", "Punishment"),
    ("Siswa menawarkan alkohol kepada peserta didik lain", "Punishment"),
    ("Siswa terbukti menjadi perantara barang terlarang", "Punishment"),
    ("Siswa mengajak teman menggunakan minuman keras", "Punishment"),
    ("Siswa terlibat transaksi barang terlarang di sekolah", "Punishment"),
    ("Siswa membawa psikotropika tanpa hak dan izin", "Punishment"),
    ("Siswa terbukti menggunakan zat adiktif terlarang", "Punishment"),
    ("Siswa kedapatan menyebarkan minuman keras kepada teman", "Punishment"),
    ("Siswa terlibat kepemilikan narkotika berdasarkan laporan resmi", "Punishment"),
    ("Siswa terbukti melakukan pelanggaran berat terkait alkohol", "Punishment"),
    ("Siswa kedapatan memakai obat terlarang saat jam sekolah", "Punishment"),
    ("Siswa menyimpan minuman keras di lingkungan sekolah", "Punishment"),
    ("Siswa membawa barang terlarang saat kegiatan sekolah berlangsung", "Punishment"),
    ("Siswa terbukti terlibat penyalahgunaan zat berbahaya", "Punishment"),
    ("Siswa kedapatan membawa psikotropika saat pemeriksaan", "Punishment"),
    ("Siswa terlibat penggunaan narkotika bersama teman sekolah", "Punishment"),
    ("Siswa terbukti melanggar tata tertib terkait narkoba", "Punishment"),
    ("Siswa menggunakan zat terlarang di area sekolah", "Punishment"),
    ("Siswa membawa alkohol ketika mengikuti kegiatan sekolah", "Punishment"),
    ("Siswa terlibat pelanggaran berat penggunaan minuman keras", "Punishment"),
    ("Siswa terbukti menyimpan barang terlarang di loker sekolah", "Punishment"),
    ("Siswa kedapatan membawa zat adiktif tanpa izin", "Punishment"),
    ("Siswa terbukti mengonsumsi alkohol bersama siswa lain", "Punishment"),
    ("Siswa mengedarkan barang terlarang kepada peserta didik", "Punishment"),
    ("Siswa terbukti melakukan transaksi barang terlarang", "Punishment"),
    ("Siswa terlibat penggunaan psikotropika di sekolah", "Punishment"),
    ("Siswa membawa minuman keras saat kegiatan luar sekolah", "Punishment"),
    ("Siswa kedapatan memiliki narkotika berdasarkan pemeriksaan", "Punishment"),
    ("Siswa terbukti memakai zat berbahaya di lingkungan sekolah", "Punishment"),
    ("Siswa terlibat penyebaran alkohol kepada teman sekolah", "Punishment"),
    ("Siswa membawa obat terlarang tanpa keterangan medis", "Punishment"),
    ("Siswa terbukti melanggar aturan sekolah terkait narkoba", "Punishment"),
    ("Siswa kedapatan menyimpan alkohol di tas pribadi", "Punishment"),
    ("Siswa menggunakan barang terlarang saat kegiatan sekolah", "Punishment"),
    ("Siswa terbukti menjadi pengguna zat adiktif", "Punishment"),
    ("Siswa mengajak teman menggunakan barang terlarang", "Punishment"),
    ("Siswa terlibat pelanggaran berat terkait psikotropika", "Punishment"),
    ("Siswa kedapatan bermain judi online di lingkungan sekolah", "Punishment"),
    ("Siswa terbukti melakukan taruhan online saat jam pelajaran", "Punishment"),
    ("Siswa menggunakan aplikasi judi online di area sekolah", "Punishment"),
    ("Siswa mengakses situs perjudian menggunakan fasilitas sekolah", "Punishment"),
    ("Siswa terlibat aktivitas perjudian online bersama teman", "Punishment"),
    ("Siswa kedapatan melakukan transaksi judi online", "Punishment"),
    ("Siswa terbukti mempromosikan perjudian online kepada siswa lain", "Punishment"),
    ("Siswa menyebarkan tautan judi online di grup kelas", "Punishment"),
    ("Siswa mengajak teman mengikuti permainan judi online", "Punishment"),
    ("Siswa menggunakan perangkat sekolah untuk aktivitas perjudian", "Punishment"),
    ("Siswa terbukti melakukan deposit pada aplikasi judi online", "Punishment"),
    ("Siswa kedapatan bermain judi online saat kegiatan belajar", "Punishment"),
    ("Siswa terlibat pelanggaran berat terkait perjudian online", "Punishment"),
    ("Siswa terbukti menyimpan aplikasi judi online di perangkat sekolah", "Punishment"),
    ("Siswa melakukan aktivitas taruhan online di lingkungan sekolah", "Punishment"),
    ("Siswa kedapatan mengakses konten perjudian saat jam sekolah", "Punishment"),
    ("Siswa terbukti melanggar aturan sekolah terkait judi online", "Punishment"),
    ("Siswa mengajak peserta didik lain bermain judi online", "Punishment"),
    ("Siswa terlibat penyebaran informasi perjudian online", "Punishment"),
    ("Siswa kedapatan aktif dalam aktivitas perjudian digital", "Punishment"),
    ("Siswa terbukti melakukan perjudian online berulang", "Punishment"),
    ("Siswa membawa perangkat berisi aplikasi perjudian online", "Punishment"),
    ("Siswa terlibat penggunaan akun judi online di sekolah", "Punishment"),
    ("Siswa kedapatan bermain taruhan digital saat pembelajaran", "Punishment"),
    ("Siswa terbukti melakukan aktivitas perjudian melalui internet sekolah", "Punishment"),
    ("Siswa menyebarkan promosi perjudian kepada teman sekolah", "Punishment"),
    ("Siswa melakukan pelanggaran berat berupa perjudian online", "Punishment"),
    ("Siswa terbukti terlibat aktivitas judi digital", "Punishment"),
    ("Siswa kedapatan menggunakan telepon genggam untuk perjudian online", "Punishment"),
    ("Siswa terlibat taruhan online saat berada di kelas", "Punishment"),
    ("Siswa menggunakan akses internet sekolah untuk judi online", "Punishment"),
    ("Siswa terbukti mengajak siswa lain melakukan perjudian online", "Punishment"),
    ("Siswa kedapatan menyimpan bukti transaksi perjudian online", "Punishment"),
    ("Siswa terlibat penggunaan platform judi online", "Punishment"),
    ("Siswa terbukti memainkan perjudian daring di sekolah", "Punishment"),
    ("Siswa kedapatan membuka situs taruhan online saat pelajaran", "Punishment"),
    ("Siswa melakukan pelanggaran tata tertib terkait perjudian digital", "Punishment"),
    ("Siswa terbukti aktif dalam kegiatan judi online", "Punishment"),
    ("Siswa mengakses aplikasi taruhan online di lingkungan sekolah", "Punishment"),
    ("Siswa terlibat aktivitas perjudian melalui perangkat pribadi", "Punishment"),
    ("Siswa kedapatan melakukan judi online bersama teman sekolah", "Punishment"),
    ("Siswa terbukti melanggar disiplin sekolah terkait perjudian", "Punishment"),
    ("Siswa menyimpan riwayat perjudian online pada perangkat sekolah", "Punishment"),
    ("Siswa kedapatan melakukan aktivitas taruhan digital berulang", "Punishment"),
    ("Siswa terbukti melakukan perjudian online di area sekolah", "Punishment"),
    ("Siswa terlibat pelanggaran sangat berat sesuai tata tertib sekolah", "Punishment"),
    ("Siswa melakukan tindakan terlarang dengan pembuktian resmi sekolah", "Punishment"),
    ("Siswa terbukti melanggar aturan sekolah kategori pelanggaran berat sekali", "Punishment"),
    ("Siswa kedapatan merokok di lingkungan sekolah", "Punishment"),
    ("Siswa berkelahi dengan teman di area sekolah", "Punishment"),
    ("Siswa membawa rokok ke dalam kelas", "Punishment"),
    ("Siswa membolos saat jam pelajaran berlangsung", "Punishment"),
    ("Siswa keluar sekolah tanpa izin guru", "Punishment"),
    ("Siswa melakukan perundungan terhadap teman kelas", "Punishment"),
    ("Siswa berkata kasar kepada guru", "Punishment"),
    ("Siswa merusak fasilitas sekolah dengan sengaja", "Punishment"),
    ("Siswa terlibat tawuran antar sekolah", "Punishment"),
    ("Siswa membawa benda tajam ke sekolah", "Punishment"),
    ("Siswa mengancam teman di lingkungan sekolah", "Punishment"),
    ("Siswa mencontek secara berulang saat ujian", "Punishment"),
    ("Siswa memalsukan tanda tangan orang tua", "Punishment"),
    ("Siswa mengambil barang milik teman tanpa izin", "Punishment"),
    ("Siswa menyebarkan video perkelahian di sekolah", "Punishment"),
    ("Siswa melakukan vandalisme pada meja kelas", "Punishment"),
    ("Siswa tidak masuk sekolah tanpa keterangan selama beberapa hari", "Punishment"),
    ("Siswa bermain judi saat jam sekolah", "Punishment"),
    ("Siswa membuat keributan besar di kelas", "Punishment"),
    ("Siswa menyalakan petasan di lingkungan sekolah", "Punishment"),
    ("Siswa menghina teman secara berlebihan", "Punishment"),
    ("Siswa sengaja memicu perkelahian antar siswa", "Punishment"),
    ("Siswa membawa minuman keras ke sekolah", "Punishment"),
    ("Siswa menggunakan ponsel saat ujian berlangsung", "Punishment"),
    ("Siswa melawan perintah guru di kelas", "Punishment"),
    ("Siswa mencoret dinding sekolah dengan kata tidak pantas", "Punishment"),
    ("Siswa mengintimidasi adik kelas di sekolah", "Punishment"),
    ("Siswa melakukan pemalakan terhadap teman", "Punishment"),
    ("Siswa merusak komputer laboratorium sekolah", "Punishment"),
    ("Siswa kabur saat kegiatan upacara berlangsung", "Punishment"),
    ("Siswa tidur berulang kali saat pelajaran berlangsung", "Punishment"),
    ("Siswa membawa kartu permainan judi ke sekolah", "Punishment"),
    ("Siswa menyebarkan berita bohong tentang guru", "Punishment"),
    ("Siswa berteriak kasar kepada teman di kelas", "Punishment"),
    ("Siswa memukul teman saat kegiatan belajar", "Punishment"),
    ("Siswa sengaja menghilangkan barang milik sekolah", "Punishment"),
    ("Siswa memprovokasi teman untuk bolos bersama", "Punishment"),
    ("Siswa membuat kelompok tawuran antar kelas", "Punishment"),
    ("Siswa merusak kursi kelas dengan sengaja", "Punishment"),
    ("Siswa mengakses situs terlarang menggunakan komputer sekolah", "Punishment"),
    ("Siswa memalsukan surat izin tidak masuk sekolah", "Punishment"),
    ("Siswa membawa vape ke lingkungan sekolah", "Punishment"),
    ("Siswa merekam guru tanpa izin saat pembelajaran", "Punishment"),
    ("Siswa mengganggu kegiatan belajar secara terus menerus", "Punishment"),
    ("Siswa melempar barang ke arah teman di kelas", "Punishment"),
    ("Siswa tidak mengikuti ujian tanpa alasan jelas", "Punishment"),
    ("Siswa melakukan bullying secara verbal kepada teman", "Punishment"),
    ("Siswa sengaja mengunci teman di dalam kelas", "Punishment"),
    ("Siswa membawa gambar tidak pantas ke sekolah", "Punishment"),
    ("Siswa memaksa teman memberikan uang jajan", "Punishment"),
    ("Siswa menyebarkan hinaan melalui media sosial sekolah", "Punishment"),
    ("Siswa memanjat pagar sekolah untuk keluar saat jam pelajaran", "Punishment"),
    ("Siswa bermain game saat guru menjelaskan materi", "Punishment"),
    ("Siswa sengaja mematikan listrik ruang kelas", "Punishment"),
    ("Siswa menolak hukuman yang diberikan guru", "Punishment"),
    ("Siswa membuat kerusuhan saat kegiatan sekolah", "Punishment"),
    ("Siswa memukul meja hingga mengganggu kelas", "Punishment"),
    ("Siswa mengajak teman meninggalkan kelas tanpa izin", "Punishment"),
    ("Siswa membakar kertas di dalam ruang kelas", "Punishment"),
    ("Siswa merusak tanaman di lingkungan sekolah", "Punishment"),
    ("Siswa mengganggu teman saat ujian berlangsung", "Punishment"),
    ("Siswa menggunakan kata tidak sopan kepada pegawai sekolah", "Punishment"),
    ("Siswa menyembunyikan barang milik teman kelas", "Punishment"),
    ("Siswa membawa speaker dan memutar musik keras saat pelajaran", "Punishment"),
    ("Siswa sengaja terlambat masuk kelas setiap hari", "Punishment"),
    ("Siswa memancing keributan di lingkungan sekolah", "Punishment"),
    ("Siswa melakukan tindakan tidak disiplin secara berulang", "Punishment"),
    ("Siswa tidak memakai atribut sekolah setelah diperingatkan", "Punishment"),
    ("Siswa menghapus data komputer laboratorium sekolah", "Punishment"),
    ("Siswa memukul pintu kelas saat marah", "Punishment"),
    ("Siswa menyebarkan foto teman tanpa izin", "Punishment"),
    ("Siswa mengolok teman hingga menangis", "Punishment"),
    ("Siswa melempar sampah ke arah teman", "Punishment"),
    ("Siswa berlari keluar kelas saat pelajaran berlangsung", "Punishment"),
    ("Siswa memanjat jendela kelas ketika guru mengajar", "Punishment"),
    ("Siswa memotong antrean kantin dan membuat keributan", "Punishment"),
    ("Siswa mengganggu kelas lain saat pembelajaran berlangsung", "Punishment"),
    ("Siswa membawa korek api ke sekolah", "Punishment"),
    ("Siswa sengaja menyembunyikan buku perpustakaan", "Punishment"),
    ("Siswa membentak guru ketika ditegur", "Punishment"),
    ("Siswa merusak proyektor kelas dengan sengaja", "Punishment"),
    ("Siswa tidak mengikuti aturan sekolah secara berulang", "Punishment"),
    ("Siswa membuat akun palsu untuk menghina teman", "Punishment"),
    ("Siswa menghasut teman untuk melawan guru", "Punishment"),
    ("Siswa membolos saat kegiatan praktik berlangsung", "Punishment"),
    ("Siswa tertangkap merokok di toilet sekolah", "Punishment"),
    ("Siswa menendang meja kelas ketika emosi", "Punishment"),
    ("Siswa menyebarkan rumor negatif tentang teman", "Punishment"),
    ("Siswa membawa senjata mainan menyerupai asli ke sekolah", "Punishment"),
    ("Siswa mengganggu jalannya presentasi teman", "Punishment"),
    ("Siswa sengaja membuat kelas menjadi kotor", "Punishment"),
    ("Siswa mencuri uang teman di kelas", "Punishment"),
    ("Siswa memukul kaca jendela sekolah", "Punishment"),
    ("Siswa menginjak tanaman sekolah hingga rusak", "Punishment"),
    ("Siswa menulis kata kasar pada papan kelas", "Punishment"),
    ("Siswa kabur sebelum jam pelajaran selesai", "Punishment"),
    ("Siswa bermain kartu saat pembelajaran berlangsung", "Punishment"),
    ("Siswa tidur di belakang kelas saat guru menjelaskan", "Punishment"),
    ("Siswa membuat video ejekan terhadap teman sekolah", "Punishment"),
    ("Siswa menolak mengikuti kegiatan sekolah wajib", "Punishment"),
    ("Siswa menyebarkan jawaban ujian kepada teman", "Punishment"),
    ("Siswa melakukan pelanggaran tata tertib secara terus menerus", "Punishment"),
    ("Siswa terlambat masuk kelas tanpa alasan jelas", "Punishment"),
    ("Siswa tidak memakai atribut sekolah lengkap", "Punishment"),
    ("Siswa keluar kelas tanpa izin guru", "Punishment"),
    ("Siswa bermain handphone saat pembelajaran berlangsung", "Punishment"),
    ("Siswa berbicara saat guru menjelaskan materi", "Punishment"),
    ("Siswa tidur pada saat jam pelajaran", "Punishment"),
    ("Siswa tidak mengerjakan tugas sekolah", "Punishment"),
    ("Siswa membuat keributan di dalam kelas", "Punishment"),
    ("Siswa bercanda berlebihan saat pembelajaran", "Punishment"),
    ("Siswa tidak mengikuti upacara tanpa keterangan", "Punishment"),
    ("Siswa membuang sampah sembarangan di lingkungan sekolah", "Punishment"),
    ("Siswa tidak memakai dasi sesuai aturan sekolah", "Punishment"),
    ("Siswa tidak memakai ikat pinggang sekolah", "Punishment"),
    ("Siswa memakai sepatu tidak sesuai ketentuan", "Punishment"),
    ("Siswa datang terlambat mengikuti upacara", "Punishment"),
    ("Siswa tidak membawa perlengkapan belajar", "Punishment"),
    ("Siswa mengganggu teman saat belajar", "Punishment"),
    ("Siswa makan di dalam kelas saat pelajaran", "Punishment"),
    ("Siswa tidak memperhatikan guru ketika pembelajaran", "Punishment"),
    ("Siswa sering izin keluar kelas tanpa alasan penting", "Punishment"),
    ("Siswa mencoret meja dan fasilitas sekolah", "Punishment"),
    ("Siswa berbicara kasar kepada teman", "Punishment"),
    ("Siswa bermain saat kegiatan belajar berlangsung", "Punishment"),
    ("Siswa tidak mengikuti piket kelas", "Punishment"),
    ("Siswa terlambat mengumpulkan tugas sekolah", "Punishment"),
    ("Siswa bercanda saat kegiatan upacara berlangsung", "Punishment"),
    ("Siswa menggunakan aksesoris tidak sesuai aturan", "Punishment"),
    ("Siswa memakai rambut tidak rapi", "Punishment"),
    ("Siswa tidak memakai seragam sesuai jadwal", "Punishment"),
    ("Siswa bermain game saat jam pelajaran", "Punishment"),
    ("Siswa tidak hadir tanpa konfirmasi wali kelas", "Punishment"),
    ("Siswa ribut saat proses pembelajaran", "Punishment"),
    ("Siswa berpindah kelas tanpa izin", "Punishment"),
    ("Siswa tidak mengikuti kegiatan sekolah wajib", "Punishment"),
    ("Siswa mengabaikan instruksi guru di kelas", "Punishment"),
    ("Siswa menggunakan bahasa kurang sopan", "Punishment"),
    ("Siswa duduk di kantin saat jam pelajaran", "Punishment"),
    ("Siswa tidak menjaga kebersihan kelas", "Punishment"),
    ("Siswa membuat gaduh di lingkungan sekolah", "Punishment"),
    ("Siswa bercanda secara berlebihan di kelas", "Punishment"),
    ("Siswa mengganggu konsentrasi teman belajar", "Punishment"),
    ("Siswa tidak membawa buku pelajaran", "Punishment"),
    ("Siswa menyontek tugas teman", "Punishment"),
    ("Siswa meninggalkan kelas sebelum pelajaran selesai", "Punishment"),
    ("Siswa tidak mengikuti senam pagi sekolah", "Punishment"),
    ("Siswa memakai jaket saat pembelajaran berlangsung", "Punishment"),
    ("Siswa tidak memakai kaos kaki sesuai aturan", "Punishment"),
    ("Siswa terlambat kembali setelah jam istirahat", "Punishment"),
    ("Siswa memainkan musik saat jam pelajaran", "Punishment"),
    ("Siswa tidak mematuhi tata tertib kelas", "Punishment"),
    ("Siswa berbicara keras saat guru mengajar", "Punishment"),
    ("Siswa duduk santai saat upacara berlangsung", "Punishment"),
    ("Siswa bercanda ketika guru memberikan tugas", "Punishment"),
    ("Siswa tidak mengikuti doa bersama sekolah", "Punishment"),
    ("Siswa menyembunyikan barang milik teman", "Punishment"),
    ("Siswa mengotori dinding kelas", "Punishment"),
    ("Siswa tidak mengikuti instruksi piket harian", "Punishment"),
    ("Siswa mengganggu kelas lain saat pembelajaran", "Punishment"),
    ("Siswa berlari di koridor sekolah saat jam belajar", "Punishment"),
    ("Siswa membawa makanan ke laboratorium", "Punishment"),
    ("Siswa membuat suara gaduh di kelas", "Punishment"),
    ("Siswa tidak memakai name tag sekolah", "Punishment"),
    ("Siswa tidak menjaga kerapihan kelas", "Punishment"),
    ("Siswa menggunakan kata tidak pantas kepada teman", "Punishment"),
    ("Siswa bermain bola di dalam kelas", "Punishment"),
    ("Siswa menunda tugas yang diberikan guru", "Punishment"),
    ("Siswa tidak mengikuti apel pagi sekolah", "Punishment"),
    ("Siswa mengganggu teman yang sedang presentasi", "Punishment"),
    ("Siswa terlambat masuk setelah pergantian jam pelajaran", "Punishment"),
    ("Siswa berbicara sendiri saat guru menjelaskan", "Punishment"),
    ("Siswa memakai sandal di lingkungan sekolah", "Punishment"),
    ("Siswa mengabaikan tugas piket kelas", "Punishment"),
    ("Siswa bercanda saat kegiatan ibadah sekolah", "Punishment"),
    ("Siswa meminjam barang teman tanpa izin", "Punishment"),
    ("Siswa tidak mematuhi aturan laboratorium", "Punishment"),
    ("Siswa keluar area sekolah tanpa izin", "Punishment"),
    ("Siswa duduk di meja kelas saat pembelajaran", "Punishment"),
    ("Siswa memainkan alat musik saat jam belajar", "Punishment"),
    ("Siswa tidak mengikuti kegiatan literasi sekolah", "Punishment"),
    ("Siswa membuat keramaian di perpustakaan", "Punishment"),
    ("Siswa membawa kartu pelajar milik teman", "Punishment"),
    ("Siswa tidak mematuhi arahan pengurus kelas", "Punishment"),
    ("Siswa tidur di perpustakaan saat jam pelajaran", "Punishment"),
    ("Siswa tidak menjaga ketertiban kelas", "Punishment"),
    ("Siswa makan saat guru menjelaskan pelajaran", "Punishment"),
    ("Siswa sering berpindah tempat duduk tanpa izin", "Punishment"),
    ("Siswa terlambat mengikuti kegiatan ekstrakurikuler", "Punishment"),
    ("Siswa bermain air di lingkungan sekolah", "Punishment"),
    ("Siswa tidak menghormati teman saat berbicara", "Punishment"),
    ("Siswa mengganggu jalannya diskusi kelas", "Punishment"),
    ("Siswa tidak memakai pakaian olahraga sesuai aturan", "Punishment"),
    ("Siswa duduk di lantai koridor sekolah", "Punishment"),
    ("Siswa mengobrol saat ujian berlangsung", "Punishment"),
    ("Siswa tidak menjaga fasilitas sekolah dengan baik", "Punishment"),
    ("Siswa bermain kartu saat jam istirahat di kelas", "Punishment"),
    ("Siswa menyembunyikan perlengkapan belajar teman", "Punishment"),
    ("Siswa tidak mengikuti kegiatan kebersihan kelas", "Punishment"),
    ("Siswa berbicara saat pengarahan sekolah berlangsung", "Punishment"),
    ("Siswa memakai pakaian tidak sesuai tata tertib", "Punishment"),
    ("Siswa meninggalkan sampah di bawah meja kelas", "Punishment"),
    ("Siswa membuat candaan berlebihan saat pembelajaran", "Punishment"),
    ("Siswa tidak disiplin saat antre di kantin", "Punishment"),
    ("siswa terlambat masuk kelas", "Punishment"),
    ("siswa datang terlambat saat upacara", "Punishment"),
    ("siswa tidak memakai atribut lengkap", "Punishment"),
    ("siswa tidak menggunakan dasi sekolah", "Punishment"),
    ("siswa tidak memakai ikat pinggang", "Punishment"),
    ("siswa memakai sepatu tidak sesuai aturan", "Punishment"),
    ("siswa rambut tidak rapi", "Punishment"),
    ("siswa berbicara saat guru menjelaskan", "Punishment"),
    ("siswa bercanda saat pembelajaran berlangsung", "Punishment"),
    ("siswa tidak membawa buku pelajaran", "Punishment"),
    ("siswa tidak mengerjakan tugas rumah", "Punishment"),
    ("siswa tidur di dalam kelas", "Punishment"),
    ("siswa bermain handphone saat pelajaran", "Punishment"),
    ("siswa makan di dalam kelas", "Punishment"),
    ("siswa keluar kelas tanpa izin", "Punishment"),
    ("siswa duduk berpindah pindah saat pelajaran", "Punishment"),
    ("siswa ribut di dalam kelas", "Punishment"),
    ("siswa tidak memperhatikan guru", "Punishment"),
    ("siswa terlambat mengumpulkan tugas", "Punishment"),
    ("siswa memakai seragam tidak rapi", "Punishment"),
    ("siswa tidak memasukkan baju", "Punishment"),
    ("siswa memakai jaket saat pembelajaran", "Punishment"),
    ("siswa berbicara kasar kepada teman", "Punishment"),
    ("siswa mengganggu teman saat belajar", "Punishment"),
    ("siswa membuang sampah sembarangan", "Punishment"),
    ("siswa mencoret meja kelas", "Punishment"),
    ("siswa tidak mengikuti piket kelas", "Punishment"),
    ("siswa bermain saat jam pelajaran", "Punishment"),
    ("siswa bercermin saat pembelajaran", "Punishment"),
    ("siswa memakai aksesoris berlebihan", "Punishment"),
    ("siswa tidak memakai kaos kaki", "Punishment"),
    ("siswa memakai sandal ke sekolah", "Punishment"),
    ("siswa membawa makanan ke laboratorium", "Punishment"),
    ("siswa tertawa berlebihan di kelas", "Punishment"),
    ("siswa menyanyi saat guru menjelaskan", "Punishment"),
    ("siswa tidak membawa alat praktik", "Punishment"),
    ("siswa datang terlambat setelah istirahat", "Punishment"),
    ("siswa bermain game di kelas", "Punishment"),
    ("siswa tidak menjaga kebersihan kelas", "Punishment"),
    ("siswa duduk di atas meja", "Punishment"),
    ("siswa berbicara sendiri saat pelajaran", "Punishment"),
    ("siswa izin terlalu lama kembali ke kelas", "Punishment"),
    ("siswa memakai rambut panjang tidak sesuai aturan", "Punishment"),
    ("siswa tidak memakai name tag", "Punishment"),
    ("siswa memakai seragam olahraga di luar jadwal", "Punishment"),
    ("siswa mencontek pekerjaan teman", "Punishment"),
    ("siswa tidak mengikuti apel pagi", "Punishment"),
    ("siswa membuat keributan saat pergantian jam", "Punishment"),
    ("siswa terlambat masuk setelah bel berbunyi", "Punishment"),
    ("siswa tidak membawa perlengkapan sekolah", "Punishment"),
    ("siswa mengobrol saat ujian berlangsung", "Punishment"),
    ("siswa tidak merapikan kursi setelah belajar", "Punishment"),
    ("siswa bermain lempar kertas di kelas", "Punishment"),
    ("siswa meminjam barang tanpa izin", "Punishment"),
    ("siswa menyalakan musik saat pelajaran", "Punishment"),
    ("siswa tidak hadir piket tanpa alasan", "Punishment"),
    ("siswa membuat suara gaduh di kelas", "Punishment"),
    ("siswa menggunakan bahasa tidak sopan", "Punishment"),
    ("siswa memakai topi di dalam kelas", "Punishment"),
    ("siswa berjalan jalan saat pelajaran", "Punishment"),
    ("siswa tidak mengikuti instruksi guru", "Punishment"),
    ("siswa terlambat mengikuti kegiatan sekolah", "Punishment"),
    ("siswa bermain di koridor saat jam belajar", "Punishment"),
    ("siswa tidak menyimpan sepatu pada tempatnya", "Punishment"),
    ("siswa membawa kartu permainan ke sekolah", "Punishment"),
    ("siswa tidak menjaga kerapihan kelas", "Punishment"),
    ("siswa membuka laptop untuk bermain game", "Punishment"),
    ("siswa tidak fokus saat pembelajaran", "Punishment"),
    ("siswa mencorat coret buku teman", "Punishment"),
    ("siswa mengganggu kelompok lain saat diskusi", "Punishment"),
    ("siswa bercanda berlebihan saat praktik", "Punishment"),
    ("siswa tidak memakai pakaian praktik lengkap", "Punishment"),
    ("siswa menggunakan earphone saat guru menjelaskan", "Punishment"),
    ("siswa menunda pengumpulan tugas", "Punishment"),
    ("siswa mengabaikan teguran guru", "Punishment"),
    ("siswa membawa mainan ke kelas", "Punishment"),
    ("siswa bermain bola di dalam kelas", "Punishment"),
    ("siswa berdiri saat pelajaran berlangsung tanpa izin", "Punishment"),
    ("siswa tidak membawa kartu pelajar", "Punishment"),
    ("siswa sering izin keluar kelas", "Punishment"),
    ("siswa mengganggu konsentrasi teman", "Punishment"),
    ("siswa tidak membersihkan alat praktik", "Punishment"),
    ("siswa berbicara keras di perpustakaan", "Punishment"),
    ("siswa tidak mengikuti aturan antre", "Punishment"),
    ("siswa membuat kegaduhan saat istirahat", "Punishment"),
    ("siswa memotong pembicaraan guru", "Punishment"),
    ("siswa tidak disiplin waktu masuk kelas", "Punishment"),
    ("siswa memakai pakaian tidak sesuai ketentuan", "Punishment"),
    ("siswa meninggalkan kelas sebelum pelajaran selesai", "Punishment"),
    ("siswa mengobrol saat presentasi teman", "Punishment"),
    ("siswa tidak mengikuti tata tertib kelas", "Punishment"),
    ("siswa membawa minuman ke laboratorium", "Punishment"),
    ("siswa bermain media sosial saat belajar", "Punishment"),
    ("siswa tidak membawa catatan pelajaran", "Punishment"),
    ("siswa duduk santai saat upacara", "Punishment"),
    ("siswa tidak memperhatikan saat briefing", "Punishment"),
    ("siswa mengotori lingkungan sekolah", "Punishment"),
    ("siswa telat mengikuti kegiatan ekstrakurikuler", "Punishment"),
    ("siswa membuat candaan saat pembelajaran serius", "Punishment"),
    ("siswa tidak menjaga ketertiban kelas", "Punishment"),
    ("siswa bermain saat guru meninggalkan kelas", "Punishment"),
    ("siswa tidak menaati aturan sekolah", "Punishment"),
    ("Siswa selalu mengerjakan tugas tepat waktu", "Reward"),
    ("Siswa rajin mengikuti pembelajaran setiap hari", "Reward"),
    ("Siswa rutin hadir tanpa terlambat", "Reward"),
    ("Siswa selalu menyelesaikan pekerjaan rumah", "Reward"),
    ("Siswa rajin membaca materi pelajaran", "Reward"),
    ("Siswa aktif belajar mandiri di kelas", "Reward"),
    ("Siswa konsisten mengumpulkan tugas harian", "Reward"),
    ("Siswa tidak pernah menunda pekerjaan sekolah", "Reward"),
    ("Siswa rajin mengikuti kegiatan belajar tambahan", "Reward"),
    ("Siswa disiplin dalam menyelesaikan latihan", "Reward"),
    ("Siswa selalu hadir dalam kegiatan sekolah", "Reward"),
    ("Siswa rajin mencatat materi pelajaran", "Reward"),
    ("Siswa tekun belajar saat jam pelajaran", "Reward"),
    ("Siswa selalu membawa perlengkapan belajar lengkap", "Reward"),
    ("Siswa rajin mengikuti praktik di laboratorium", "Reward"),
    ("Siswa berusaha memahami materi dengan baik", "Reward"),
    ("Siswa selalu fokus saat pembelajaran berlangsung", "Reward"),
    ("Siswa rutin mengikuti kegiatan literasi sekolah", "Reward"),
    ("Siswa rajin berdiskusi dengan teman kelompok", "Reward"),
    ("Siswa selalu mempersiapkan diri sebelum ujian", "Reward"),
    ("Siswa disiplin mengatur jadwal belajar", "Reward"),
    ("Siswa rutin mengikuti bimbingan belajar", "Reward"),
    ("Siswa aktif menyelesaikan latihan soal", "Reward"),
    ("Siswa rajin datang lebih awal ke kelas", "Reward"),
    ("Siswa selalu memperhatikan penjelasan guru", "Reward"),
    ("Siswa tidak pernah absen tanpa keterangan", "Reward"),
    ("Siswa rajin mengulang materi di rumah", "Reward"),
    ("Siswa konsisten menjaga semangat belajar", "Reward"),
    ("Siswa aktif mencari referensi tambahan pelajaran", "Reward"),
    ("Siswa rajin mengikuti kegiatan akademik", "Reward"),
    ("Siswa selalu menyimpan catatan pelajaran dengan rapi", "Reward"),
    ("Siswa rutin mempelajari materi sebelum pelajaran dimulai", "Reward"),
    ("Siswa rajin membantu teman memahami pelajaran", "Reward"),
    ("Siswa selalu mengerjakan latihan yang diberikan guru", "Reward"),
    ("Siswa disiplin mengikuti jadwal piket kelas", "Reward"),
    ("Siswa rajin mengikuti evaluasi pembelajaran", "Reward"),
    ("Siswa selalu menyelesaikan tugas kelompok", "Reward"),
    ("Siswa rutin hadir dalam kegiatan ekstrakurikuler", "Reward"),
    ("Siswa rajin belajar meskipun tidak ada ujian", "Reward"),
    ("Siswa selalu menunjukkan tanggung jawab belajar", "Reward"),
    ("Siswa disiplin menjaga kehadiran sekolah", "Reward"),
    ("Siswa rajin mengikuti arahan guru", "Reward"),
    ("Siswa aktif bertanya ketika belum memahami materi", "Reward"),
    ("Siswa selalu memanfaatkan waktu belajar dengan baik", "Reward"),
    ("Siswa rajin mengikuti kegiatan praktik sekolah", "Reward"),
    ("Siswa rutin menyelesaikan laporan praktik", "Reward"),
    ("Siswa disiplin membawa buku pelajaran", "Reward"),
    ("Siswa rajin memperbaiki nilai pelajaran", "Reward"),
    ("Siswa selalu berusaha meningkatkan prestasi belajar", "Reward"),
    ("Siswa tekun mengikuti seluruh kegiatan pembelajaran", "Reward"),
    ("Siswa konsisten menjaga kedisiplinan belajar", "Reward"),
    ("Siswa rajin mengerjakan soal latihan tambahan", "Reward"),
    ("Siswa selalu siap mengikuti pelajaran", "Reward"),
    ("Siswa aktif dalam kegiatan belajar kelompok", "Reward"),
    ("Siswa rutin belajar bersama teman", "Reward"),
    ("Siswa rajin mencari materi tambahan di perpustakaan", "Reward"),
    ("Siswa disiplin mengumpulkan laporan tepat waktu", "Reward"),
    ("Siswa selalu hadir tepat waktu di kelas", "Reward"),
    ("Siswa rajin mengikuti pengarahan sekolah", "Reward"),
    ("Siswa konsisten menyelesaikan tugas mingguan", "Reward"),
    ("Siswa tekun mempelajari materi praktik", "Reward"),
    ("Siswa rajin mengikuti simulasi ujian", "Reward"),
    ("Siswa selalu serius saat pembelajaran berlangsung", "Reward"),
    ("Siswa aktif mengikuti kegiatan pendidikan karakter", "Reward"),
    ("Siswa rajin menjaga kebersihan area belajar", "Reward"),
    ("Siswa disiplin menaati aturan kelas", "Reward"),
    ("Siswa rutin mengikuti kegiatan pembiasaan pagi", "Reward"),
    ("Siswa rajin mempelajari materi sebelumnya", "Reward"),
    ("Siswa selalu siap saat presentasi kelas", "Reward"),
    ("Siswa aktif menyumbangkan ide dalam diskusi", "Reward"),
    ("Siswa disiplin menyusun jadwal belajar pribadi", "Reward"),
    ("Siswa rajin menghadiri kegiatan pembinaan sekolah", "Reward"),
    ("Siswa selalu berusaha memahami tugas dengan baik", "Reward"),
    ("Siswa rutin mengulang materi setelah pembelajaran", "Reward"),
    ("Siswa rajin bertanya kepada guru mengenai pelajaran", "Reward"),
    ("Siswa selalu mengerjakan tugas tanpa disuruh", "Reward"),
    ("Siswa aktif mengikuti pembelajaran daring maupun luring", "Reward"),
    ("Siswa disiplin dalam penggunaan waktu belajar", "Reward"),
    ("Siswa rajin mengikuti kegiatan sekolah setiap minggu", "Reward"),
    ("Siswa tekun menyelesaikan proyek pembelajaran", "Reward"),
    ("Siswa konsisten menjaga motivasi belajar", "Reward"),
    ("Siswa rajin mengikuti kegiatan praktik industri", "Reward"),
    ("Siswa disiplin menyelesaikan target pembelajaran", "Reward"),
    ("Siswa rutin mempersiapkan alat praktik", "Reward"),
    ("Siswa aktif mengikuti seminar pendidikan sekolah", "Reward"),
    ("Siswa rajin membantu kegiatan akademik kelas", "Reward"),
    ("Siswa disiplin mengikuti tata tertib sekolah", "Reward"),
    ("Siswa selalu bersemangat mengikuti pembelajaran", "Reward"),
    ("Siswa rajin memperhatikan instruksi guru", "Reward"),
    ("Siswa aktif mempelajari teknologi pembelajaran baru", "Reward"),
    ("Siswa rutin membuat rangkuman pelajaran", "Reward"),
    ("Siswa disiplin menjaga ketertiban kelas", "Reward"),
    ("Siswa rajin menyelesaikan revisi tugas", "Reward"),
    ("Siswa aktif mengikuti lomba akademik sekolah", "Reward"),
    ("Siswa tekun belajar untuk meningkatkan nilai", "Reward"),
    ("Siswa selalu menunjukkan sikap rajin belajar", "Reward"),
    ("Siswa rutin melatih kemampuan akademik", "Reward"),
    ("Siswa disiplin mengikuti seluruh mata pelajaran", "Reward"),
    ("Siswa rajin mengembangkan kemampuan diri", "Reward"),
    ("Siswa aktif mengikuti kegiatan edukatif sekolah", "Reward"),
    ("Siswa selalu menjaga konsistensi belajar", "Reward"),
    ("Siswa rajin berlatih soal setiap hari", "Reward"),
    ("Siswa selalu memakai seragam lengkap dan rapi", "Reward"),
    ("Siswa menjaga kerapihan pakaian sekolah setiap hari", "Reward"),
    ("Siswa tampil rapi saat mengikuti pembelajaran", "Reward"),
    ("Siswa menggunakan atribut sekolah dengan lengkap", "Reward"),
    ("Siswa menjaga kebersihan dan kerapihan diri", "Reward"),
    ("Siswa memakai sepatu sesuai aturan sekolah", "Reward"),
    ("Siswa selalu berpakaian sopan dan rapi", "Reward"),
    ("Siswa hadir dengan penampilan bersih dan rapi", "Reward"),
    ("Siswa menjaga rambut tetap rapi sesuai aturan", "Reward"),
    ("Siswa disiplin dalam menggunakan seragam sekolah", "Reward"),
    ("Siswa konsisten memakai atribut lengkap", "Reward"),
    ("Siswa terlihat rapi saat upacara sekolah", "Reward"),
    ("Siswa menjaga penampilan dengan baik di sekolah", "Reward"),
    ("Siswa selalu memakai pakaian sesuai tata tertib", "Reward"),
    ("Siswa memperhatikan kerapihan saat berada di kelas", "Reward"),
    ("Siswa menjaga kebersihan seragam setiap hari", "Reward"),
    ("Siswa berpakaian rapi dan sopan di lingkungan sekolah", "Reward"),
    ("Siswa tidak pernah melanggar aturan berpakaian", "Reward"),
    ("Siswa tampil bersih dan teratur setiap hari", "Reward"),
    ("Siswa menjaga kerapihan rambut dan seragam", "Reward"),
    ("Siswa menggunakan dasi dan atribut lengkap", "Reward"),
    ("Siswa selalu merapikan pakaian sebelum masuk kelas", "Reward"),
    ("Siswa menjaga sepatu tetap bersih dan rapi", "Reward"),
    ("Siswa disiplin menjaga penampilan sekolah", "Reward"),
    ("Siswa memakai seragam sesuai ketentuan sekolah", "Reward"),
    ("Siswa menjaga kerapihan saat kegiatan sekolah", "Reward"),
    ("Siswa selalu tampil sopan di lingkungan sekolah", "Reward"),
    ("Siswa menjaga kebersihan diri dengan baik", "Reward"),
    ("Siswa konsisten menjaga atribut sekolah lengkap", "Reward"),
    ("Siswa berpenampilan rapi saat kegiatan belajar", "Reward"),
    ("Siswa selalu menjaga tata tertib berpakaian", "Reward"),
    ("Siswa tampil bersih dan sopan setiap hari", "Reward"),
    ("Siswa menjaga pakaian tetap bersih di sekolah", "Reward"),
    ("Siswa selalu memperhatikan penampilan diri", "Reward"),
    ("Siswa berpakaian sesuai aturan sekolah", "Reward"),
    ("Siswa hadir dengan atribut yang lengkap", "Reward"),
    ("Siswa menjaga rambut tetap pendek dan rapi", "Reward"),
    ("Siswa disiplin menggunakan seragam harian", "Reward"),
    ("Siswa tampil rapi saat kegiatan upacara", "Reward"),
    ("Siswa menjaga kerapihan selama kegiatan belajar", "Reward"),
    ("Siswa selalu memakai ikat pinggang sekolah", "Reward"),
    ("Siswa memakai pakaian yang bersih dan rapi", "Reward"),
    ("Siswa selalu tampil tertib dan sopan", "Reward"),
    ("Siswa menjaga penampilan dengan disiplin", "Reward"),
    ("Siswa memperhatikan kebersihan dan kerapihan pakaian", "Reward"),
    ("Siswa memakai seragam dengan benar", "Reward"),
    ("Siswa tidak pernah lupa memakai atribut sekolah", "Reward"),
    ("Siswa menjaga kebersihan sepatu dan pakaian", "Reward"),
    ("Siswa konsisten menjaga kerapihan di sekolah", "Reward"),
    ("Siswa berpakaian sopan selama pembelajaran", "Reward"),
    ("Siswa selalu menjaga rambut sesuai tata tertib", "Reward"),
    ("Siswa tampil rapi dan percaya diri di sekolah", "Reward"),
    ("Siswa menggunakan seragam lengkap saat upacara", "Reward"),
    ("Siswa disiplin menjaga tata tertib berpakaian", "Reward"),
    ("Siswa menjaga penampilan selama berada di sekolah", "Reward"),
    ("Siswa selalu memakai atribut sesuai aturan", "Reward"),
    ("Siswa menjaga kebersihan pakaian sekolah", "Reward"),
    ("Siswa berpenampilan sopan dan teratur", "Reward"),
    ("Siswa selalu hadir dengan pakaian rapi", "Reward"),
    ("Siswa menjaga kerapihan selama kegiatan praktik", "Reward"),
    ("Siswa disiplin menjaga kebersihan diri", "Reward"),
    ("Siswa selalu memakai seragam dengan lengkap", "Reward"),
    ("Siswa menjaga penampilan agar tetap rapi", "Reward"),
    ("Siswa memperhatikan tata tertib berpakaian sekolah", "Reward"),
    ("Siswa tampil bersih selama kegiatan belajar", "Reward"),
    ("Siswa menjaga atribut sekolah tetap lengkap", "Reward"),
    ("Siswa memakai pakaian sesuai ketentuan harian", "Reward"),
    ("Siswa konsisten tampil rapi setiap hari", "Reward"),
    ("Siswa menjaga kebersihan dan penampilan diri", "Reward"),
    ("Siswa selalu tertib dalam berpakaian", "Reward"),
    ("Siswa menjaga seragam tetap bersih dan sopan", "Reward"),
    ("Siswa memakai atribut lengkap saat pembelajaran", "Reward"),
    ("Siswa selalu tampil rapi dalam kegiatan sekolah", "Reward"),
    ("Siswa menjaga kebersihan rambut dan pakaian", "Reward"),
    ("Siswa disiplin dalam menjaga penampilan", "Reward"),
    ("Siswa selalu berpakaian sesuai aturan", "Reward"),
    ("Siswa menjaga kerapihan saat berada di lingkungan sekolah", "Reward"),
    ("Siswa memakai seragam sekolah dengan baik", "Reward"),
    ("Siswa tampil sopan dan rapi setiap hari", "Reward"),
    ("Siswa selalu menjaga kebersihan sepatu sekolah", "Reward"),
    ("Siswa menggunakan atribut sekolah secara lengkap", "Reward"),
    ("Siswa menjaga tata tertib berpakaian dengan disiplin", "Reward"),
    ("Siswa tampil rapi saat mengikuti kegiatan sekolah", "Reward"),
    ("Siswa memperhatikan kebersihan diri dan pakaian", "Reward"),
    ("Siswa disiplin menjaga seragam sekolah", "Reward"),
    ("Siswa selalu hadir dengan penampilan rapi", "Reward"),
    ("Siswa menjaga pakaian tetap sopan dan bersih", "Reward"),
    ("Siswa menggunakan seragam sesuai tata tertib", "Reward"),
    ("Siswa selalu menjaga kerapihan diri di sekolah", "Reward"),
    ("Siswa tampil bersih dan tertib saat pembelajaran", "Reward"),
    ("Siswa menjaga atribut tetap lengkap setiap hari", "Reward"),
    ("Siswa selalu berpakaian rapi di lingkungan sekolah", "Reward"),
    ("Siswa disiplin menjaga kebersihan dan penampilan", "Reward"),
    ("Siswa menjaga rambut dan pakaian tetap rapi", "Reward"),
    ("Siswa selalu memakai seragam dengan tertib", "Reward"),
    ("Siswa tampil sopan selama kegiatan belajar", "Reward"),
    ("Siswa menjaga penampilan sesuai aturan sekolah", "Reward"),
    ("Siswa selalu memperhatikan kebersihan pakaian", "Reward"),
    ("Siswa menjaga kerapihan dan kesopanan berpakaian", "Reward"),
    ("Siswa tampil rapi dan disiplin setiap hari", "Reward"),
    ("Siswa memperoleh nilai tertinggi pada mata pelajaran produktif", "Reward"),
    ("Siswa mendapatkan hasil ujian dengan nilai sangat baik", "Reward"),
    ("Siswa menunjukkan prestasi akademik yang konsisten", "Reward"),
    ("Siswa memperoleh rata rata nilai di atas standar sekolah", "Reward"),
    ("Siswa berhasil meraih peringkat terbaik di kelas", "Reward"),
    ("Siswa mendapatkan nilai sempurna pada tugas harian", "Reward"),
    ("Siswa memiliki kemampuan akademik yang sangat baik", "Reward"),
    ("Siswa menunjukkan peningkatan nilai yang signifikan", "Reward"),
    ("Siswa aktif belajar dan memperoleh hasil memuaskan", "Reward"),
    ("Siswa mendapatkan nilai tinggi pada ujian semester", "Reward"),
    ("Siswa berhasil menyelesaikan tugas dengan sangat baik", "Reward"),
    ("Siswa memperoleh penghargaan akademik dari sekolah", "Reward"),
    ("Siswa konsisten memperoleh nilai di atas rata rata", "Reward"),
    ("Siswa menunjukkan kemampuan memahami materi dengan baik", "Reward"),
    ("Siswa berhasil mencapai target akademik sekolah", "Reward"),
    ("Siswa memperoleh nilai praktik terbaik di kelas", "Reward"),
    ("Siswa memiliki prestasi belajar yang membanggakan", "Reward"),
    ("Siswa mendapatkan hasil belajar yang sangat memuaskan", "Reward"),
    ("Siswa berhasil memperoleh juara akademik kelas", "Reward"),
    ("Siswa menunjukkan semangat belajar yang tinggi", "Reward"),
    ("Siswa mampu menyelesaikan soal dengan tepat", "Reward"),
    ("Siswa memperoleh nilai terbaik pada ujian harian", "Reward"),
    ("Siswa menunjukkan kemampuan analisis yang baik", "Reward"),
    ("Siswa aktif mengikuti kegiatan akademik sekolah", "Reward"),
    ("Siswa memperoleh hasil evaluasi yang sangat baik", "Reward"),
    ("Siswa mendapatkan prestasi akademik yang membanggakan", "Reward"),
    ("Siswa berhasil mempertahankan nilai tinggi setiap semester", "Reward"),
    ("Siswa menunjukkan disiplin dalam kegiatan belajar", "Reward"),
    ("Siswa memperoleh hasil praktik yang sangat baik", "Reward"),
    ("Siswa mampu memahami materi pembelajaran dengan cepat", "Reward"),
    ("Siswa mendapatkan nilai tinggi dalam semua mata pelajaran", "Reward"),
    ("Siswa menunjukkan ketekunan dalam belajar", "Reward"),
    ("Siswa berhasil menyelesaikan proyek akademik dengan baik", "Reward"),
    ("Siswa memperoleh nilai terbaik pada mata pelajaran kejuruan", "Reward"),
    ("Siswa aktif mengikuti lomba akademik sekolah", "Reward"),
    ("Siswa menunjukkan kemampuan berpikir kritis yang baik", "Reward"),
    ("Siswa memperoleh penghargaan sebagai Siswa berprestasi", "Reward"),
    ("Siswa berhasil mencapai nilai di atas KKM", "Reward"),
    ("Siswa menunjukkan konsistensi dalam prestasi belajar", "Reward"),
    ("Siswa memiliki kemampuan akademik yang unggul", "Reward"),
    ("Siswa mendapatkan hasil belajar terbaik di kelas", "Reward"),
    ("Siswa memperoleh nilai sangat baik pada ujian praktik", "Reward"),
    ("Siswa berhasil meraih prestasi akademik sekolah", "Reward"),
    ("Siswa menunjukkan tanggung jawab terhadap tugas belajar", "Reward"),
    ("Siswa memperoleh nilai memuaskan dalam kegiatan pembelajaran", "Reward"),
    ("Siswa berhasil mencapai prestasi akademik yang tinggi", "Reward"),
    ("Siswa aktif dalam kegiatan pembelajaran di kelas", "Reward"),
    ("Siswa memperoleh hasil ujian yang sangat memuaskan", "Reward"),
    ("Siswa mampu menyelesaikan tugas akademik tepat waktu", "Reward"),
    ("Siswa mendapatkan nilai tinggi secara konsisten", "Reward"),
    ("Siswa memperoleh prestasi terbaik dalam bidang akademik", "Reward"),
    ("Siswa menunjukkan kemampuan belajar yang sangat baik", "Reward"),
    ("Siswa berhasil memperoleh nilai unggul pada ujian akhir", "Reward"),
    ("Siswa memperoleh hasil akademik yang membanggakan", "Reward"),
    ("Siswa aktif mengembangkan kemampuan akademik", "Reward"),
    ("Siswa menunjukkan dedikasi tinggi terhadap pembelajaran", "Reward"),
    ("Siswa berhasil memperoleh nilai terbaik pada kelas produktif", "Reward"),
    ("Siswa memperoleh penghargaan atas prestasi akademik", "Reward"),
    ("Siswa menunjukkan kemampuan memahami teori dan praktik", "Reward"),
    ("Siswa memperoleh nilai tinggi pada evaluasi pembelajaran", "Reward"),
    ("Siswa berhasil mencapai target nilai semester", "Reward"),
    ("Siswa memiliki motivasi belajar yang sangat tinggi", "Reward"),
    ("Siswa menunjukkan kemampuan akademik secara konsisten", "Reward"),
    ("Siswa memperoleh hasil belajar yang optimal", "Reward"),
    ("Siswa aktif mengikuti pembelajaran dengan baik", "Reward"),
    ("Siswa berhasil mendapatkan nilai terbaik pada ujian sekolah", "Reward"),
    ("Siswa memperoleh pencapaian akademik yang sangat baik", "Reward"),
    ("Siswa menunjukkan kualitas belajar yang unggul", "Reward"),
    ("Siswa berhasil mempertahankan prestasi akademik", "Reward"),
    ("Siswa memperoleh hasil penilaian terbaik di kelas", "Reward"),
    ("Siswa aktif menyelesaikan tugas akademik", "Reward"),
    ("Siswa memperoleh nilai memuaskan pada seluruh mata pelajaran", "Reward"),
    ("Siswa menunjukkan kemampuan akademik di atas rata rata", "Reward"),
    ("Siswa berhasil mendapatkan prestasi belajar terbaik", "Reward"),
    ("Siswa memperoleh nilai praktik yang sangat memuaskan", "Reward"),
    ("Siswa menunjukkan semangat tinggi dalam belajar", "Reward"),
    ("Siswa memperoleh hasil akademik yang konsisten", "Reward"),
    ("Siswa berhasil mencapai nilai unggulan sekolah", "Reward"),
    ("Siswa menunjukkan kemampuan menyelesaikan soal dengan baik", "Reward"),
    ("Siswa memperoleh prestasi akademik yang sangat memuaskan", "Reward"),
    ("Siswa aktif meningkatkan kemampuan belajar", "Reward"),
    ("Siswa memperoleh nilai terbaik pada ujian kompetensi", "Reward"),
    ("Siswa berhasil mencapai hasil belajar optimal", "Reward"),
    ("Siswa menunjukkan kemampuan akademik yang membanggakan", "Reward"),
    ("Siswa memperoleh hasil evaluasi akademik terbaik", "Reward"),
    ("Siswa berhasil mempertahankan nilai akademik tinggi", "Reward"),
    ("Siswa menunjukkan prestasi belajar yang sangat baik", "Reward"),
    ("Siswa memperoleh penghargaan Siswa berprestasi akademik", "Reward"),
    ("Siswa berhasil memperoleh nilai sangat memuaskan", "Reward"),
    ("Siswa menunjukkan kemampuan belajar secara aktif", "Reward"),
    ("Siswa memperoleh hasil ujian praktik terbaik", "Reward"),
    ("Siswa berhasil mencapai prestasi akademik unggul", "Reward"),
    ("Siswa memperoleh nilai terbaik pada kegiatan evaluasi", "Reward"),
    ("Siswa menunjukkan kemampuan akademik yang luar biasa", "Reward"),
    ("Siswa berhasil memperoleh hasil belajar terbaik", "Reward"),
    ("Siswa memperoleh nilai akademik tinggi secara konsisten", "Reward"),
    ("Siswa menunjukkan kualitas akademik yang sangat baik", "Reward"),
    ("Siswa berhasil mendapatkan penghargaan akademik sekolah", "Reward"),
    ("Siswa memperoleh hasil pembelajaran yang sangat baik", "Reward"),
    ("Siswa menunjukkan kemampuan unggul dalam bidang akademik", "Reward"),
    ("Siswa berhasil mencapai prestasi belajar yang membanggakan", "Reward"),
    ("siswa ikut merapikan buku di perpustakaan sekolah", "Reward"),
    ("siswa membantu petugas merapikan buku perpustakaan", "Reward"),
    ("siswa merapikan buku perpustakaan dengan rapi", "Reward"),
    ("siswa dengan inisiatif merapikan buku di perpustakaan", "Reward"),
    ("siswa membersihkan dan merapikan rak buku perpustakaan", "Reward"),
    ("siswa membantu merapikan buku pelajaran di perpustakaan", "Reward"),
    ("siswa terlambat masuk sekolah", "Punishment"),
    ("siswa telat datang ke sekolah", "Punishment"),
    ("siswa kesiangan dan datang terlambat", "Punishment"),
    ("siswa membolos saat jam pelajaran", "Punishment"),
    ("siswa tidak mengerjakan tugas", "Punishment"),
    ("siswa tidak masuk sekolah tanpa keterangan", "Punishment"),
    ("siswa merokok di lingkungan sekolah", "Punishment"),
    ("siswa berkelahi dengan teman", "Punishment"),
    ("siswa mencontek saat ujian", "Punishment"),
    ("siswa membuang sampah sembarangan", "Punishment"),
    ("siswa tidak memakai seragam lengkap", "Punishment"),
    ("siswa rambutnya panjang dan tidak rapi", "Punishment"),
    ("siswa tidak membawa buku pelajaran", "Punishment"),
    ("siswa bermain hp saat guru menjelaskan", "Punishment"),
    ("siswa berkata tidak sopan kepada guru", "Punishment"),
    ("siswa berbohong kepada wali kelas", "Punishment"),
    ("siswa mencoret coret meja dan kursi", "Punishment"),
    ("siswa tidak memakai atribut sekolah", "Punishment"),
    ("siswa datang terlambat dan tidak mengerjakan tugas", "Punishment"),
    ("siswa terlambat masuk setelah jam istirahat", "Punishment"),
])

# ============================================================
# MASTER POIN (dari tabel master_poin)
# ============================================================
master_poin.extend([
    ("Punishment", "Pembawa, pemakai, penjual, pengedar alkohol, judi online, narkoba dan atau psikotropika dengan pembuktian aturan sekolah", 100),
    ("Punishment", "Merampas atau mencuri milik orang lain baik di sekolah atau di luar sekolah", 100),
    ("Punishment", "Berkelahi atau penganiayaan, membuat keonaran yang mengganggu ketertiban umum", 100),
    ("Punishment", "Hamil, menghamili, pemerkosaan atau menikah", 100),
    ("Punishment", "Ditato, tindik, tendok oleh sendiri ataupun orang lain", 100),
    ("Punishment", "Memalsukan surat atau tanda tangan pejabat sekolah", 50),
    ("Punishment", "Menghina, memfitnah, merendahkan Kepala Sekolah, Guru, TU, dan atau Karyawan/ Petugas Sekolah", 50),
    ("Punishment", "Membawa senjata tajam, senjata api atau alat lain yang tidak berhubungan dengan keperluan sekolah", 50),
    ("Punishment", "Membawa bacaan, gambar, VCD, HP atau media lain yang bersifat pornografi", 50),
    ("Punishment", "Merusak dan menghilangkan barang milik sekolah dan atau milik orang lain", 50),
    ("Punishment", "Merusak lingkungan sekolah dan atau lingkungan umum", 50),
    ("Punishment", "Pelecehan seksual", 50),
    ("Punishment", "Menyalahgunakan keuangan sekolah", 30),
    ("Punishment", "Merokok di lingkungan sekolah dan atau di luar sekolah dengan memakai seragam atau atribut sekolah", 30),
    ("Punishment", "Kabur atau meninggalkan kelas (sekolah) tanpa izin guru pengajar", 30),
    ("Punishment", "Memalsukan surat atau tanda tangan orang tua / wali", 30),
    ("Punishment", "Tidak masuk sekolah tanpa keterangan 3 hari dalam sepekan", 30),
    ("Punishment", "Tidak masuk sekolah tanpa keterangan lebih dari 3 hari dalam sebulan", 30),
    ("Punishment", "Membuat coretan atau gambar pada pakaian, tas, lingkungan sekolah atau di tempat umum", 30),
    ("Punishment", "Memakai aksesoris di lingkungan sekolah (jaket, sweater, topi, gelang, sabuk, kalung, perhiasan dll)", 15),
    ("Punishment", "Berpakaian seragam dengan ukuran, bahan, atau potongan yang tidak sesuai dengan ketentuan sekolah", 15),
    ("Punishment", "Membawa rokok ke sekolah", 15),
    ("Punishment", "Memakai pakaian yang tidak sesuai dengan ketentuan hari yang berlaku", 15),
    ("Punishment", "Tidak mengikuti upacara bendera, atau kegiatan pagi/ siang tanpa alasan", 15),
    ("Punishment", "Tidak memakai pakaian praktik selama melaksanakan pelajaran praktik", 15),
    ("Punishment", "Berpenampilan tidak sesuai dengan ketentuan sekolah (rambut gondrong, atau di cat, tidak memakai atribut sekolah yang berlaku, makeup berlebihan, dll)", 15),
    ("Punishment", "Melompat benteng sekolah untuk masuk mengikuti pelajaran", 15),
    ("Punishment", "Penyalahgunaan media sosial tidak sesuai dengan peruntukan pembelajaran (konten video/foto, status dan chat)", 15),
    ("Punishment", "Menghilangkan buku saku, Siswa wajib mengganti yang baru", 5),
    ("Punishment", "Tidak membawa buku saku, point pelanggaran bertambah", 5),
    ("Punishment", "Tidak masuk sekolah tanpa keterangan", 5),
    ("Punishment", "Terlambat masuk, dipintu gerbang terhitung mulai pukul 07.15", 5),
    ("Punishment", "Keluar lingkungan sekolah saat istirahat tanpa izin piket", 5),
    ("Punishment", "Membuang sampah sembarangan", 5),
    ("Punishment", "Baju dikeluarkan", 5),
    ("Punishment", "Berbicara kasar, tidak sopan, tidak senonoh", 5),
    ("Reward", "Siswa berhasil meraih prestasi tingkat kecamatan", 25),
    ("Reward", "Siswa menunjukkan prestasi tingkat kecamatan", 25),
    ("Reward", "Siswa memiliki prestasi tingkat kecamatan", 25),
    ("Reward", "Siswa aktif mengikuti kompetisi tingkat kecamatan", 25),
    ("Reward", "Prestasi tingkat kecamatan", 25),
    ("Reward", "Siswa memperoleh prestasi tingkat kecamatan", 25),
    ("Reward", "Siswa memperoleh prestasi tingkat kabupaten", 50),
    ("Reward", "Siswa berhasil meraih prestasi tingkat kabupaten", 50),
    ("Reward", "Siswa mendapatkan prestasi tingkat kabupaten", 50),
    ("Reward", "Siswa menorehkan prestasi tingkat kabupaten", 50),
    ("Reward", "Siswa memperoleh prestasi tingkat provinsi", 75),
    ("Reward", "Siswa berhasil meraih prestasi tingkat provinsi", 75),
    ("Reward", "Siswa mendapatkan penghargaan prestasi tingkat provinsi", 75),
    ("Reward", "Siswa menunjukkan prestasi membanggakan tingkat provinsi", 75),
    ("Reward", "aktif bertanya saat pembelajaran", 20),
    ("Reward", "aktif mengikuti diskusi kelas", 20),
    ("Reward", "selalu hadir tepat waktu", 20),
    ("Reward", "membantu teman belajar", 20),
    ("Reward", "rajin mengerjakan tugas", 20),
    ("Reward", "berpartisipasi dalam kegiatan sekolah", 20),
    ("Reward", "aktif dalam organisasi sekolah", 20),
    ("Reward", "menjaga kebersihan kelas", 20),
    ("Reward", "berbicara sopan kepada guru", 20),
    ("Reward", "mengikuti upacara dengan tertib", 20),
    ("Reward", "selalu memakai atribut lengkap", 20),
    ("Reward", "rajin membaca di perpustakaan", 20),
    ("Reward", "menjadi ketua kelompok yang baik", 20),
    ("Reward", "membantu guru saat kegiatan kelas", 20),
    ("Reward", "aktif saat presentasi kelompok", 20),
    ("Reward", "mendapat nilai terbaik di kelas", 20),
    ("Reward", "selalu disiplin dalam belajar", 20),
    ("Reward", "bertanggung jawab terhadap tugas", 20),
    ("Reward", "aktif mengikuti ekstrakurikuler", 20),
    ("Reward", "menjadi teladan bagi teman", 20),
    ("Reward", "berprestasi dalam lomba sekolah", 20),
    ("Reward", "aktif mengikuti praktik pembelajaran", 20),
    ("Reward", "selalu menjaga kerapihan seragam", 20),
    ("Reward", "datang lebih awal ke sekolah", 20),
    ("Reward", "menyelesaikan tugas tepat waktu", 20),
    ("Reward", "aktif memberikan ide saat diskusi", 20),
    ("Reward", "rajin mengikuti kegiatan literasi", 20),
    ("Reward", "memiliki sikap sopan dan santun", 20),
    ("Reward", "membantu menjaga kebersihan lingkungan", 20),
    ("Reward", "aktif dalam kegiatan sosial sekolah", 20),
    ("Reward", "menjadi Siswa inspiratif di kelas", 20),
    ("Reward", "berinisiatif membantu teman kesulitan", 20),
    ("Reward", "konsisten hadir tanpa alpha", 20),
    ("Reward", "aktif mengikuti kegiatan keagamaan", 20),
    ("Reward", "menjadi anggota organisasi yang disiplin", 20),
    ("Reward", "berprestasi di bidang olahraga", 20),
    ("Reward", "berprestasi di bidang akademik", 20),
    ("Reward", "berprestasi di bidang seni", 20),
    ("Reward", "selalu menjaga ketertiban kelas", 20),
    ("Reward", "aktif menjawab pertanyaan guru", 20),
    ("Reward", "memiliki semangat belajar tinggi", 20),
    ("Reward", "mengikuti kegiatan sekolah dengan baik", 20),
    ("Reward", "menjadi Siswa paling disiplin", 20),
    ("Reward", "rajin mengikuti piket kelas", 20),
    ("Reward", "aktif dalam kerja kelompok", 20),
    ("Reward", "menjadi Siswa dengan perilaku baik", 20),
    ("Reward", "selalu menghormati guru dan teman", 20),
    ("Reward", "aktif mengikuti seminar sekolah", 20),
    ("Reward", "memiliki tanggung jawab tinggi", 20),
    ("Reward", "aktif dalam kegiatan pramuka", 20),
    ("Reward", "membantu teman memahami pelajaran", 20),
    ("Reward", "selalu menjaga nama baik sekolah", 20),
    ("Reward", "aktif dalam lomba antar kelas", 20),
    ("Reward", "berhasil meraih juara kelas", 20),
    ("Reward", "menjadi Siswa dengan kehadiran terbaik", 20),
    ("Reward", "rajin mengikuti pelatihan sekolah", 20),
    ("Reward", "aktif memberikan solusi saat diskusi", 20),
    ("Reward", "menjadi Siswa teladan sekolah", 20),
    ("Reward", "aktif dalam kegiatan kebersihan sekolah", 20),
    ("Reward", "rajin mengumpulkan tugas harian", 20),
    ("Reward", "memiliki komunikasi yang baik", 20),
    ("Reward", "aktif dalam kegiatan kelas", 20),
    ("Reward", "mampu bekerja sama dengan baik", 20),
    ("Reward", "selalu bersikap jujur", 20),
    ("Reward", "aktif mengikuti kegiatan positif", 20),
    ("Reward", "berani tampil presentasi di depan kelas", 20),
    ("Reward", "membantu guru menyiapkan kelas", 20),
    ("Reward", "aktif dalam kegiatan olahraga sekolah", 20),
    ("Reward", "memiliki sikap disiplin tinggi", 20),
    ("Reward", "aktif memberikan motivasi kepada teman", 20),
    ("Reward", "selalu mematuhi tata tertib sekolah", 20),
    ("Reward", "menjadi Siswa dengan etika baik", 20),
    ("Reward", "aktif mengikuti kegiatan bakti sosial", 20),
    ("Reward", "rajin belajar mandiri", 20),
    ("Reward", "menjadi pengurus kelas yang bertanggung jawab", 20),
    ("Reward", "aktif menjaga ketenangan kelas", 20),
    ("Reward", "berprestasi dalam kompetisi sekolah", 20),
    ("Reward", "aktif mengikuti kegiatan teknologi sekolah", 20),
    ("Reward", "memiliki jiwa kepemimpinan yang baik", 20),
    ("Reward", "aktif membantu kegiatan sekolah", 20),
    ("Reward", "menjadi Siswa paling rajin", 20),
    ("Reward", "aktif dalam kegiatan kewirausahaan sekolah", 20),
    ("Reward", "memiliki perilaku santun di sekolah", 20),
    ("Reward", "aktif dalam kegiatan keilmuan", 20),
    ("Reward", "selalu menjaga kebersihan meja kelas", 20),
    ("Reward", "aktif membantu teman saat praktik", 20),
    ("Reward", "menjadi Siswa yang komunikatif", 20),
    ("Reward", "aktif mengikuti pembelajaran praktik", 20),
    ("Reward", "berprestasi dalam ujian sekolah", 20),
    ("Reward", "aktif dalam kegiatan lingkungan sekolah", 20),
    ("Reward", "selalu memberikan contoh baik", 20),
    ("Reward", "aktif mengikuti kegiatan budaya sekolah", 20),
    ("Reward", "menjadi Siswa dengan semangat tinggi", 20),
    ("Reward", "aktif berkontribusi dalam kelompok", 20),
    ("Reward", "rajin mengikuti pembinaan sekolah", 20),
    ("Reward", "aktif mendukung kegiatan kelas", 20),
    ("Reward", "menjadi Siswa yang peduli lingkungan", 20),
    ("Reward", "aktif mengikuti pengarahan guru", 20),
    ("Reward", "berhasil meningkatkan prestasi belajar", 20),
    ("Reward", "aktif menjaga fasilitas sekolah", 20),
    ("Reward", "selalu menunjukkan sikap positif", 20),
    ("Reward", "aktif dalam kegiatan edukatif sekolah", 20),
    ("Reward", "Disiplin Tugas", 20),
    ("Reward", "Rajin Belajar", 20),
    ("Reward", "Tepat Waktu", 20),
    ("Reward", "Disiplin Kehadiran", 20),
    ("Reward", "Tanggung Jawab Belajar", 20),
    ("Reward", "Konsisten Belajar", 20),
    ("Reward", "Prestasi Akademik", 20),
    ("Reward", "Nilai Unggul", 20),
    ("Reward", "Juara Akademik", 20),
    ("Reward", "Target Akademik Tercapai", 20),
    ("Reward", "Kemampuan Akademik", 20),
    ("Reward", "Prestasi Belajar", 20),
    ("Reward", "Sopan Santun", 20),
    ("Reward", "Disiplin Sikap", 20),
    ("Reward", "Semangat Belajar", 20),
    ("Reward", "Tanggung Jawab", 20),
    ("Reward", "Percaya Diri", 20),
    ("Reward", "Mandiri", 20),
    ("Reward", "Disiplin Berpakaian", 20),
    ("Reward", "Kerapihan Diri", 20),
    ("Reward", "Taat Tata Tertib", 20),
    ("Reward", "Peduli Kebersihan", 20),
    ("Reward", "Penampilan Rapi", 20),
    ("Reward", "Aktif Diskusi", 20),
    ("Reward", "Aktif Bertanya", 20),
    ("Reward", "Aktif Akademik", 20),
    ("Reward", "Aktif Literasi", 20),
    ("Reward", "Aktif Kegiatan Edukatif", 20),
    ("Reward", "Kolaborasi Belajar", 20),
    ("Reward", "Peduli Teman", 20),
    ("Reward", "Kerja Sama", 20),
    ("Reward", "Membantu Teman", 20),
    ("Reward", "Peduli Lingkungan", 20),
    ("Reward", "Sikap Positif", 20),
    ("Reward", "merapikan buku di perpustakaan", 20),
    ("Reward", "membantu merapikan buku perpustakaan", 20),
    ("Reward", "merapikan buku dan membersihkan perpustakaan", 20),
    ("Reward", "merapikan buku perpustakaan", 20),
    ("Reward", "siswa merapikan buku di perpustakaan", 20),
    ("Reward", "membantu merapikan buku di perpustakaan", 20),
    ("Punishment", "terlambat masuk", 10),
    ("Punishment", "kesiangan", 10),
    ("Punishment", "membolos", 15),
    ("Punishment", "tidak mengerjakan tugas", 10),
    ("Punishment", "tidak masuk sekolah", 10),
    ("Punishment", "merokok di sekolah", 30),
    ("Punishment", "berkelahi", 50),
    ("Punishment", "mencontek", 15),
    ("Punishment", "mencoret coret", 10),
    ("Punishment", "membuang sampah sembarangan", 5),
    ("Punishment", "tidak memakai seragam", 10),
    ("Punishment", "rambut tidak rapi", 5),
    ("Punishment", "telat", 10),
    ("Punishment", "tidak membawa buku", 5),
    ("Punishment", "main hp saat pelajaran", 10),
    ("Punishment", "tidak sopan", 5),
    ("Punishment", "berbohong", 10),
])

# ============================================================
# EVALUASI
# ============================================================
if __name__ == '__main__':
    print("=" * 80)
    print("SKRIPSI NLP - KLASIFIKASI PERILAKU SISWA (REWARD/PUNISHMENT)")
    print("Menggunakan engine: nlp_engine.py")
    print("=" * 80)

    print(f"\nTotal data training: {len(dataset_training)} samples")
    print(f"Total aturan master_poin: {len(master_poin)} rules")

    # Convert master_poin to include sequential IDs for nlp_engine.py v2
    global master_poin
    master_poin = [(i+1, jenis, nama, poin) for i, (jenis, nama, poin) in enumerate(master_poin)]

    # Test Cases
    print("\n" + "=" * 80)
    print("UJI COBA KLASIFIKASI")
    print("=" * 80)

    test_cases = [
        "Siswa telat masuk sekolah tetapi membantu guru untuk membersihkan lingkunan sekolah",
        "Siswa telat masuk sekolah",
        "Siswa merokok di lingkungan sekolah",
        "Siswa berkelahi dengan teman di kelas",
        "Siswa selalu mengerjakan tugas tepat waktu dan disiplin",
        "Siswa meraih juara 1 lomba olahraga tingkat provinsi",
        "Siswa ikut merapikan buku di perpustakaan sekolah",
        "Siswa membawa minuman keras ke sekolah",
        "Siswa tidak memakai seragam lengkap",
        "Siswa rajin belajar dan aktif di kelas",
        "siswa bolos saat jam pelajaran",
        "siswa membantu petugas merapikan buku perpustakaan",
    ]

    for teks in test_cases:
        hasil = klasifikasi(teks)
        print(f"\nTeks  : {teks}")
        aturan = hasil.get('aturan') or {}
        print(f"Label : {hasil['label']} (Poin: {aturan.get('poin', 0)})")
        if hasil['aturan']:
            print(f"Aturan: {hasil['aturan']['nama']} ({hasil['aturan']['poin']} poin)")

    # EVALUASI AKURASI
    print("\n" + "=" * 80)
    print("EVALUASI AKURASI MENGGUNAKAN TRAINING DATA")
    print("=" * 80)

    y_true = []
    y_pred = []

    for teks, label_asli in dataset_training:
        hasil = klasifikasi(teks)
        y_true.append(label_asli)
        y_pred.append(hasil['label'])

    tp = sum(1 for t, p in zip(y_true, y_pred) if t == 'Reward' and p == 'Reward')
    tn = sum(1 for t, p in zip(y_true, y_pred) if t == 'Punishment' and p == 'Punishment')
    fp = sum(1 for t, p in zip(y_true, y_pred) if t == 'Punishment' and p == 'Reward')
    fn = sum(1 for t, p in zip(y_true, y_pred) if t == 'Reward' and p == 'Punishment')

    accuracy = (tp + tn) / len(y_true)
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

    print(f"\nTotal Data Training: {len(y_true)}")
    print(f"Accuracy : {accuracy:.4f} ({accuracy*100:.2f}%)")
    print(f"Precision: {precision:.4f} ({precision*100:.2f}%)")
    print(f"Recall   : {recall:.4f} ({recall*100:.2f}%)")
    print(f"F1-Score : {f1:.4f} ({f1*100:.2f}%)")

    print(f"\nConfusion Matrix:")
    print(f"                Predicted")
    print(f"                Reward  Punishment")
    print(f"Actual Reward   {tp:6d}  {fn:6d}")
    print(f"       Punishment {fp:6d}  {tn:6d}")

    reward_total = tp + fn
    punishment_total = tn + fp
    print(f"\nAkurasi per Kelas:")
    print(f"Reward    : {tp}/{reward_total} ({tp/reward_total*100:.2f}%)")
    print(f"Punishment: {tn}/{punishment_total} ({tn/punishment_total*100:.2f}%)")

    # DETAIL 20 SAMPLE PERTAMA
    print("\n" + "=" * 80)
    print("DETAIL 20 SAMPLE PERTAMA")
    print("=" * 80)

    salah = 0
    benar = 0
    detail = []

    for i, (teks, label_asli) in enumerate(dataset_training[:20]):
        hasil = klasifikasi(teks)
        status = "OK" if hasil['label'] == label_asli else "FAIL"
        if hasil['label'] == label_asli:
            benar += 1
        else:
            salah += 1
        detail.append((teks[:60], label_asli, hasil['label'], status))

    print(f"{'No':<4} {'Teks':<62} {'Asli':<12} {'Pred':<12} Status")
    print("-" * 100)
    for i, (teks, asli, pred, status) in enumerate(detail, 1):
        print(f"{i:<4} {teks:<62} {asli:<12} {pred:<12} {status}")

    print(f"\nBenar: {benar}, Salah: {salah}, Akurasi: {benar/(benar+salah)*100:.2f}%")

    print("\n" + "=" * 80)
    print("SELESAI")
    print("=" * 80)
