<?php
session_start();
if (($_SESSION['status'] ?? '') !== 'login' || !in_array($_SESSION['role'] ?? '', ['Admin', 'BK', 'Kepsek'], true)) {
    header('location:index.php');
    exit();
}
include 'koneksi.php';

$pesan = $_SESSION['pesan_verifikasi'] ?? '';
$status = $_SESSION['status_verifikasi'] ?? '';
unset($_SESSION['pesan_verifikasi'], $_SESSION['status_verifikasi']);

$filter = $_GET['status'] ?? 'pending';
$filter_valid = ['pending', 'disetujui', 'ditolak', 'semua'];
if (!in_array($filter, $filter_valid, true)) $filter = 'pending';
$where = $filter === 'semua' ? '' : "WHERE lp.status_verifikasi = '" . mysqli_real_escape_string($koneksi, $filter) . "'";
$laporan = mysqli_query($koneksi, "SELECT lp.*, s.nama_siswa, s.nis, s.kelas, u.nama_lengkap AS nama_pelapor, v.nama_lengkap AS nama_verifikator
    FROM laporan_prilaku lp
    JOIN siswa s ON s.id_siswa = lp.id_siswa
    LEFT JOIN users u ON u.id_user = lp.id_user
    LEFT JOIN users v ON v.id_user = lp.id_verifikator
    $where ORDER BY lp.id_laporan DESC");
$daftar_laporan = [];
if ($laporan) {
    while ($row = mysqli_fetch_assoc($laporan)) $daftar_laporan[] = $row;
}
?>
<!DOCTYPE html>
<html lang="id"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>Verifikasi Laporan - SMKS DB</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
<style>
html, body { background:#f0f4f8; font-family:Poppins,sans-serif; -webkit-tap-highlight-color:transparent; }
.mobile-header { background:linear-gradient(135deg,#1e3a8a 0%,#4f46e5 100%); color:white; padding:15px 20px; position:sticky; top:0; z-index:100; box-shadow:0 4px 12px rgba(0,0,0,.1); }
.btn-back { color:#fff; font-size:22px; text-decoration:none; }.filter-card,.report-card { background:#fff; border:0; box-shadow:0 4px 10px rgba(0,0,0,.03); border-radius:16px; }
.report-card { padding:16px; margin-bottom:12px; }.status-pill,.badge-poin { border-radius:20px; padding:6px 11px; font-size:11px; font-weight:600; display:inline-flex; align-items:center; gap:4px; }
.report-desktop-head { background:#eef2ff; border-radius:12px; margin-bottom:8px; }.action-area { border-top:1px dashed #e2e8f0; margin-top:12px; padding-top:12px; }
.report-text { font-size:12px; color:#475569; line-height:1.6; }.meta { font-size:11px; color:#64748b; }.form-control-sm { border-radius:9px; font-size:12px; }
.foto-bukti-thumb { width:58px; height:58px; object-fit:cover; border-radius:10px; border:2px solid #e2e8f0; cursor:zoom-in; transition:transform .2s; }.foto-bukti-thumb:hover { transform:scale(1.06); border-color:#4f46e5; }
.zoom-stage { min-height:300px; max-height:65vh; overflow:auto; display:flex; align-items:center; justify-content:center; background:#0f172a; border-radius:0 0 14px 14px; }.zoom-stage img { max-width:100%; max-height:60vh; transform-origin:center; transition:transform .18s ease; }
@media(max-width:767.98px){.desktop-view{display:none!important}.page-container{padding-bottom:28px}}@media(min-width:768px){.mobile-view{display:none!important}.page-container{margin-top:30px}}
</style></head><body>
<div class="mobile-header"><div class="container d-flex align-items-center justify-content-between p-0"><div class="d-flex align-items-center gap-3"><a href="dashboard" class="btn-back"><i class="bi bi-arrow-left"></i></a><h5 class="fw-bold mb-0" style="font-size:18px">Verifikasi Laporan</h5></div><button class="btn btn-light btn-sm fw-bold rounded-pill px-3" onclick="location.reload()"><i class="bi bi-arrow-clockwise me-1"></i>Refresh</button></div></div>
<main class="container page-container px-3 mt-3">
<?php if ($pesan): ?><div class="alert alert-<?= $status === 'sukses' ? 'success' : 'danger' ?> alert-dismissible fade show rounded-3 small py-2 mb-3"><i class="bi bi-<?= $status === 'sukses' ? 'check-circle-fill' : 'exclamation-triangle-fill' ?> me-2"></i><?= htmlspecialchars($pesan) ?><button type="button" class="btn-close py-2" data-bs-dismiss="alert"></button></div><?php endif; ?>
<div class="filter-card p-3 mb-3"><div class="d-flex flex-wrap align-items-center justify-content-between gap-2"><div><div class="fw-bold text-dark small"><i class="bi bi-shield-check text-primary me-1"></i>Persetujuan Reward & Punishment</div><small class="text-muted" style="font-size:11px">Poin siswa hanya dihitung setelah laporan disetujui.</small></div><div class="btn-group btn-group-sm"><?php foreach ($filter_valid as $item): ?><a class="btn <?= $filter === $item ? 'btn-primary' : 'btn-outline-primary' ?>" href="?status=<?= $item ?>"><?= $item === 'semua' ? 'Semua' : ucfirst($item) ?></a><?php endforeach; ?></div></div></div>
<div class="desktop-view report-desktop-head row align-items-center px-3 py-2 fw-bold text-secondary small"><div class="col-md-3">Siswa / Pelapor</div><div class="col-md-2">Isi Laporan</div><div class="col-md-1 text-center">Foto</div><div class="col-md-2 text-center">Kategori & Poin</div><div class="col-md-2 text-center">Status</div><div class="col-md-2">Aksi Verifikasi</div></div>
<?php if ($daftar_laporan): foreach ($daftar_laporan as $row): $is_reward=$row['label_prediksi']==='Reward'; $is_pending=$row['status_verifikasi']==='pending'; $status_class=$is_pending?'bg-warning-subtle text-warning-emphasis':($row['status_verifikasi']==='disetujui'?'bg-success-subtle text-success':'bg-danger-subtle text-danger'); ?>
<div class="report-card">
<div class="mobile-view"><div class="d-flex justify-content-between gap-2"><div><span class="meta">NIS <?= htmlspecialchars($row['nis']) ?> · <?= htmlspecialchars($row['kelas']) ?></span><h6 class="fw-bold text-dark mb-1 mt-1" style="font-size:15px"><?= htmlspecialchars($row['nama_siswa']) ?></h6><span class="meta">Pelapor: <?= htmlspecialchars($row['nama_pelapor'] ?? '-') ?></span></div><span class="status-pill <?= $status_class ?> align-self-start"><?= strtoupper($row['status_verifikasi']) ?></span></div><div class="action-area"><div class="report-text mb-2">“<?= htmlspecialchars($row['teks_laporan']) ?>”</div><?php if (!empty($row['foto'])): ?><button type="button" class="btn p-0 border-0 bg-transparent mb-2 btn-zoom-foto" data-foto="<?= htmlspecialchars($row['foto'], ENT_QUOTES) ?>" data-nama="<?= htmlspecialchars($row['nama_siswa'], ENT_QUOTES) ?>"><img src="<?= htmlspecialchars($row['foto']) ?>" class="foto-bukti-thumb" alt="Foto bukti <?= htmlspecialchars($row['nama_siswa']) ?>"><span class="meta ms-1">Ketuk foto untuk perbesar</span></button><?php endif; ?><div class="d-flex justify-content-between align-items-center"><span class="badge-poin <?= $is_reward?'bg-success-subtle text-success':'bg-danger-subtle text-danger' ?>"><i class="bi <?= $is_reward?'bi-award-fill':'bi-exclamation-triangle-fill' ?>"></i><?= $is_reward?'+':'-' ?><?= (int)$row['poin_didapat'] ?> Poin</span><span class="meta"><?= date('d-m-Y H:i',strtotime($row['tgl_input'])) ?></span></div><?php if ($is_pending): ?><form method="post" action="proses_verifikasi_laporan.php" class="mt-3"><input type="hidden" name="id_laporan" value="<?= (int)$row['id_laporan'] ?>"><input name="catatan_verifikasi" class="form-control form-control-sm mb-2" placeholder="Catatan verifikasi (opsional)"><div class="d-flex gap-2"><button name="aksi" value="disetujui" class="btn btn-sm btn-success rounded-pill flex-fill"><i class="bi bi-check-lg"></i> Setujui</button><button name="aksi" value="ditolak" class="btn btn-sm btn-outline-danger rounded-pill flex-fill"><i class="bi bi-x-lg"></i> Tolak</button></div></form><?php else: ?><div class="meta mt-2">Catatan: <?= htmlspecialchars($row['catatan_verifikasi'] ?: '-') ?></div><?php endif; ?></div></div>
<div class="desktop-view row align-items-center"><div class="col-md-3"><div class="fw-bold text-dark small"><?= htmlspecialchars($row['nama_siswa']) ?></div><div class="meta"><?= htmlspecialchars($row['nis']) ?> · <?= htmlspecialchars($row['kelas']) ?><br>Pelapor: <?= htmlspecialchars($row['nama_pelapor'] ?? '-') ?></div></div><div class="col-md-2"><div class="report-text">“<?= htmlspecialchars($row['teks_laporan']) ?>”</div><div class="meta mt-1"><?= date('d-m-Y H:i',strtotime($row['tgl_input'])) ?></div></div><div class="col-md-1 text-center"><?php if (!empty($row['foto'])): ?><img src="<?= htmlspecialchars($row['foto']) ?>" class="foto-bukti-thumb btn-zoom-foto" data-foto="<?= htmlspecialchars($row['foto'], ENT_QUOTES) ?>" data-nama="<?= htmlspecialchars($row['nama_siswa'], ENT_QUOTES) ?>" alt="Foto bukti <?= htmlspecialchars($row['nama_siswa']) ?>"><?php else: ?><span class="meta">-</span><?php endif; ?></div><div class="col-md-2 text-center"><span class="badge-poin <?= $is_reward?'bg-success-subtle text-success':'bg-danger-subtle text-danger' ?>"><?= $is_reward?'+':'-' ?><?= (int)$row['poin_didapat'] ?> Poin</span><div class="meta mt-1"><?= htmlspecialchars($row['label_prediksi']) ?></div></div><div class="col-md-2 text-center"><span class="status-pill <?= $status_class ?>"><?= strtoupper($row['status_verifikasi']) ?></span><?php if(!$is_pending): ?><div class="meta mt-1"><?= htmlspecialchars($row['nama_verifikator'] ?? '-') ?></div><?php endif; ?></div><div class="col-md-2"><?php if($is_pending): ?><form method="post" action="proses_verifikasi_laporan.php"><input type="hidden" name="id_laporan" value="<?= (int)$row['id_laporan'] ?>"><input name="catatan_verifikasi" class="form-control form-control-sm mb-2" placeholder="Catatan (opsional)"><div class="d-flex gap-1"><button name="aksi" value="disetujui" class="btn btn-sm btn-success rounded-pill flex-fill" title="Setujui"><i class="bi bi-check-lg"></i></button><button name="aksi" value="ditolak" class="btn btn-sm btn-outline-danger rounded-pill flex-fill" title="Tolak"><i class="bi bi-x-lg"></i></button></div></form><?php else: ?><span class="meta"><?= htmlspecialchars($row['catatan_verifikasi'] ?: '-') ?></span><?php endif; ?></div></div>
</div><?php endforeach; else: ?><div class="report-card text-center text-muted py-5"><i class="bi bi-inbox fs-3 d-block mb-2"></i>Tidak ada laporan <?= $filter === 'semua' ? '' : htmlspecialchars($filter) ?>.</div><?php endif; ?>
</main><div class="modal fade" id="modalZoomFoto" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content border-0"><div class="modal-header py-2"><h6 class="modal-title fw-bold"><i class="bi bi-image me-1"></i>Foto Bukti: <span id="namaFotoZoom"></span></h6><div class="btn-group btn-group-sm me-2"><button type="button" class="btn btn-outline-secondary" id="zoomOut" title="Perkecil"><i class="bi bi-dash-lg"></i></button><button type="button" class="btn btn-outline-secondary" id="zoomReset" title="Ukuran normal">100%</button><button type="button" class="btn btn-outline-secondary" id="zoomIn" title="Perbesar"><i class="bi bi-plus-lg"></i></button></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body p-0"><div class="zoom-stage" id="zoomStage"><img id="fotoZoom" src="" alt="Foto bukti diperbesar"></div></div></div></div></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script>const modalZoom=new bootstrap.Modal(document.getElementById('modalZoomFoto')),fotoZoom=document.getElementById('fotoZoom'),namaFotoZoom=document.getElementById('namaFotoZoom');let skala=1;function aturZoom(nilai){skala=Math.min(3,Math.max(.5,nilai));fotoZoom.style.transform='scale('+skala+')';document.getElementById('zoomReset').textContent=Math.round(skala*100)+'%'}document.querySelectorAll('.btn-zoom-foto').forEach(el=>el.addEventListener('click',()=>{fotoZoom.src=el.dataset.foto;namaFotoZoom.textContent=el.dataset.nama;aturZoom(1);modalZoom.show()}));document.getElementById('zoomIn').addEventListener('click',()=>aturZoom(skala+.25));document.getElementById('zoomOut').addEventListener('click',()=>aturZoom(skala-.25));document.getElementById('zoomReset').addEventListener('click',()=>aturZoom(1));document.getElementById('zoomStage').addEventListener('wheel',e=>{e.preventDefault();aturZoom(skala+(e.deltaY<0?.1:-.1))},{passive:false});</script></body></html>
